ForJarik
RusyaNexus/ModuleThree pull request #1
Opened 2018-04-27 20:33 UTC by RusyaNexus

Up

2018-04-28 20:32 UTC, YaroslavKuchuk commented
1. Все твои коммиты должны быть информативными. Не просто "dlyaJarika", а, например, "Стартовый коммит", "Структура классов", "Поток для добавления записей", и т.д.

2018-04-28 20:42 UTC, YaroslavKuchuk commented
Тоже самое касается бранчей.

2018-04-28 20:55 UTC, YaroslavKuchuk requested changes
Пожалуйста, поменяй типы (и остальные комментарии). И обсудим в понедельник. Продлжай также. Хорошая работа! )

2018-04-28 20:55 UTC, YaroslavKuchuk commented on ModuleThreeApp/LibraryApp/DCAction.cs
> +        GetServers = 1,
Константы по порядку - 0, 1, 2

2018-04-28 20:55 UTC, YaroslavKuchuk commented on ModuleThreeApp/LibraryApp/DataCenter.cs
> +        public List<Server> Servers { get; set; } = new List<Server>();
Сможем сделать ее кастомной (отдельной) коллекцией?

2018-04-28 20:55 UTC, YaroslavKuchuk commented on ModuleThreeApp/ModuleThreeApp/LogicAction.cs
> +                            //OutputInfo(dataCenter.Servers);
Старайся не оставлять комментарии в коде.

2018-04-28 20:55 UTC, YaroslavKuchuk commented on ModuleThreeApp/ModuleThreeApp/LogicAction.cs
> +                        for (int i = 0; i < DataCenters.Count; i++)
См. выше

2018-04-28 20:55 UTC, YaroslavKuchuk commented on ModuleThreeApp/LibraryApp/Server.cs
> +        public string AdditionalPower { get; set; }
Может его стоит сделать не строкой?

2018-04-28 20:55 UTC, YaroslavKuchuk commented on ModuleThreeApp/LibraryApp/Server.cs
> +        public int BaseType { get; set; }
Как насчет enum?

2018-04-29 01:01 UTC, RusyaNexus commented on ModuleThreeApp/LibraryApp/Server.cs
> +        public int BaseType { get; set; }
Тут не совсем понял, AdditionalPower и BaseType сделать нужно enum'ами?

2018-04-29 01:02 UTC, RusyaNexus commented on ModuleThreeApp/LibraryApp/Server.cs
> +        public string AdditionalPower { get; set; }
AdditionalPower?

2018-04-29 01:02 UTC, RusyaNexus commented on ModuleThreeApp/ModuleThreeApp/LogicAction.cs
> +                            //OutputInfo(dataCenter.Servers);
Понял, уберу

2018-04-29 01:02 UTC, RusyaNexus commented on ModuleThreeApp/LibraryApp/DataCenter.cs
> +        public List<Server> Servers { get; set; } = new List<Server>();
Сделаю

2018-04-29 01:02 UTC, RusyaNexus commented on ModuleThreeApp/LibraryApp/DCAction.cs
> +        GetServers = 1,
Понял

2018-04-29 01:03 UTC, RusyaNexus commented on ModuleThreeApp/LibraryApp/DCAction.cs
> +        GetServers = 1,
И вверху по поводу dlyaYarika так же понял=) буду писать что изменилось

2018-04-30 05:17 UTC, yaku1202 commented on ModuleThreeApp/LibraryApp/Server.cs
> +        public int BaseType { get; set; }
Не, BaseType.

2018-04-30 05:18 UTC, yaku1202 commented on ModuleThreeApp/LibraryApp/Server.cs
> +        public string AdditionalPower { get; set; }
да. По-моему, это точно не строка.

2018-05-01 21:21 UTC, YaroslavKuchuk approved these changes

2018-05-01 21:21 UTC, merged